News/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'home'
urlpatterns = [

	# Introduction Apps
	path('', include('News_Account.urls')),
	path('', include('News_Pannel.urls')),
	path('', include('News_Post.urls')),
	path('', include('News_Sitesetting.urls')),

	# Url Pages
	path('', views.home_page, name='home'),

	# partial Views
	path('', views.header_partial, name='header'),
	path('', views.bottomWriter_partial, name='writer'),
	path('', views.opinion_footer_partial, name='footerpar'),

	path('ckeditor/', include('ckeditor_uploader.urls')),
	path('captcha/', include('captcha.urls')),
	path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

News_Post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('post/list/', views.PostList.as_view(), name='list'),
    path('post/detail/<int:postID>/<str:postTITLE>', views.post_detail, name='detail'),
    path('post/search/', views.searchPost.as_view(), name='search'),
    path('post/tag/<str:tagTitle>', views.searchPostTag.as_view(), name='tag'),
    path('post/category/<str:CategoryTitle>', views.searchPostCateGory.as_view(), name='category'),
    # path('post/specific/', views.postSpecific.as_view(), name='postSpecific'),      #asdfasdfasfa
    path('post/many/<int:Many>', views.postMany.as_view(), name='many'),
    path('post/time/<str:postTime>', views.postTime.as_view(), name='time'),
    path('post/comments/report/<int:commentID>/<int:postID>', views.reportComment, name='reportComment'),
    path('post/comments/remove/<int:commentID>/<int:postID>', views.removeComment, name='removeComment'),
    path('post/like', views.like_post_page, name='like'),
    path('post/fav', views.fav_post_page, name='fav'),
    path('post/recent', views.postListRecent.as_view(), name='recent'),
    path('post/most-views', views.postListMostViews.as_view(), name='mostviews'),
    path('post/popular', views.postListPopular.as_view(), name='popular'),
    path('post/hot', views.postListHot.as_view(), name='hot'),

    # Partials
    path('post/list/sidebar/list/partial', views.sidebar_list_partial),
]

templates/partials/sidebar_advers_list_post.html
{% if advers %}
<div class="b-dark c-white p-4 mt-2 radius-sm shadow">
    <div class="card no-border b-dark">
        {% for adver in advers %}
            <a href="{{ adver.link }}" target="_blank"><img src="{{ adver.image.url }}" alt="{{ adver.title }}" class="imgadvr img-fluid mt-2"></a>
        {% endfor %}
    </div>
</div>
{% endif %}

templates/partials/sidebar_listpost.html
<!-- sideBar1 -->
<div class="card no-border b-dark">
    {% if request.user.status == 'n' or request.user.status == 'v' %}
{#        <a href="{% url 'post:postSpecific' %}" class="anchor f-icon c-white b-warning text-center br-rl"> ویژه نامه </a>#}
    {% endif %}
    <div class="card-body b-dark">
        <h5 class="c-warning font-weight-bolder">دسته بندی ها</h5>
        <br>
        {% for i in categories %}
            <p class="f-small pl-3"><i class="fa fa-minus c-warning"></i><a href="{% url 'post:category' i.title %}" class="aInSidebar"> {{ i.title }} </a></p>
        {% endfor %}

    </div>

    <div class="card-body b-dark">
        <h5 class="c-warning font-weight-bolder">تعداد نمایش</h5>
        <br>
        <p class="f-small pl-3"><i class="fa fa-question c-warning"></i><a href="{% url 'post:many' '5' %}" class="aInSidebar"> نمایش <span class="number">5</span> پست اخیر </a></p>
        <p class="f-small pl-3"><i class="fa fa-question c-warning"></i><a href="{% url 'post:many' '10' %}" class="aInSidebar"> نمایش <span class="number">10</span> پست اخیر </a></p>
        <p class="f-small pl-3"><i class="fa fa-question c-warning"></i><a href="{% url 'post:many' '50' %}" class="aInSidebar"> نمایش <span class="number">50</span> پست اخیر </a></p>
        <p class="f-small pl-3"><i class="fa fa-question c-warning"></i><a href="{% url 'post:many' '100' %}" class="aInSidebar"> نمایش <span class="number">100</span> پست اخیر </a></p>

    </div>

    <div class="card-body b-dark">
        <h5 class="c-warning font-weight-bolder">گنجینه ی خبری زمان</h5>
        <br>
        <p class="f-small pl-3"><i class="fa fa-clock c-warning"></i><a href="{% url 'post:time' 'today' %}" class="aInSidebar"> اخبار امروز </a></p>
        <p class="f-small pl-3"><i class="fa fa-clock c-warning"></i><a href="{% url 'post:time' 'yesterday' %}" class="aInSidebar"> اخبار دیروز </a></p>
        <p class="f-small pl-3"><i class="fa fa-clock c-warning"></i><a href="{% url 'post:time' 'this-week' %}" class="aInSidebar"> اخبار این هفته </a></p>
        <p class="f-small pl-3"><i class="fa fa-clock c-warning"></i><a href="{% url 'post:time' 'this-month' %}" class="aInSidebar"> اخبار این ماه </a></p>
        <p class="f-small pl-3"><i class="fa fa-clock c-warning"></i><a href="{% url 'post:time' '3-month' %}" class="aInSidebar"> اخبار سه ماه اخیر </a></p>
    </div>

    <div class="card-body b-dark">
        <h5 class="c-warning font-weight-bolder">ترین های خبری</h5>
        <br>
        <p class="f-small pl-3"><i class="fa fa-file c-warning"></i><a href="{% url 'post:recent' %}" class="aInSidebar"> جدیدترین اخبار </a></p>
        <p class="f-small pl-3"><i class="fa fa-file c-warning"></i><a href="{% url 'post:mostviews' %}" class="aInSidebar"> پربازدیدترین اخبار </a></p>
        <p class="f-small pl-3"><i class="fa fa-file c-warning"></i><a href="{% url 'post:popular' %}" class="aInSidebar"> محبوب ترین اخبار </a></p>
        <p class="f-small pl-3"><i class="fa fa-file c-warning"></i><a href="{% url 'post:hot' %}" class="aInSidebar"> داغ ترین اخبار </a></p>
    </div>

</div>