News/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'home'
urlpatterns = [

	# Introduction Apps
	path('', include('News_Account.urls')),
	path('', include('News_Pannel.urls')),
	path('', include('News_Post.urls')),
	path('', include('News_Sitesetting.urls')),

	# Url Pages
	path('', views.home_page, name='home'),

	# partial Views
	path('', views.header_partial, name='header'),
	path('', views.bottomWriter_partial, name='writer'),
	path('', views.opinion_footer_partial, name='footerpar'),

	path('ckeditor/', include('ckeditor_uploader.urls')),
	path('captcha/', include('captcha.urls')),
	path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

News_Pannel/urls.py
from django.urls import path
from . import views, views_managerUser, views_managerSite

app_name = 'pannel'
urlpatterns = [
    path('user/dashboard', views.pannel_home, name='home'),
    path('user/edit', views.pannel_edit, name='edit'),
    path('user/change-pw', views.pannel_changePassword, name='changepw'),
    path('user/saved', views.pannel_saved, name='saved'),
    path('user/delete/saved/<int:postID>', views.delete_pannel_saved, name='deletepostsave'),
    path('user/send-ticket', views.pannel_send_ticket, name='sendticket'),
    path('user/send/post', views.pannel_send_post, name='sendpost'),
    path('user/send/post/tags', views.pannel_send_post_tags, name='sendposttags'),
    path('user/send/post/galleries', views.pannel_send_post_galleries, name='sendpostgalleries'),
    path('user/release/<int:postID>', views.pannel_convert_release, name='releasepost'),

    # manager User
    path('user/manager/users', views_managerUser.managerUser, name='managerUser'),
    path('user/manager/posts', views_managerUser.managerPost, name='managerPost'),
    path('user/manager/users/edit/<int:userID>', views_managerUser.managerUser_edit, name='managerUseredit'),
    path('user/manager/posts/edit/<int:postID>', views_managerUser.managerPost_edit, name='managerPostedit'),
    path('user/manager/emails', views_managerUser.manageremail, name='manageremail'),
    path('user/manager/emails/send', views_managerUser.manageremailSend, name='manageremailsend'),
    path('user/manager/emails/remove/<int:emailID>', views_managerUser.manageremailSend_remove, name='manageremailremove'),
    path('user/manager/emails/send/<int:emailID>', views_managerUser.manageremailSend_sendmail, name='manageremailsendMail'),
    path('user/manager/charts', views_managerUser.managercharts, name='managercharts'),
    path('user/manager/notifications', views_managerUser.manager_notifications, name='managernotifications'),

    # manager Site
    path('user/manager/site/contact-us', views_managerSite.manager_contactus, name='managercontact'),
    path('user/manager/site/opinions', views_managerSite.manager_opinions, name='manageropinion'),
    path('user/manager/site/advertisings', views_managerSite.manager_advertisings, name='managerads'),
    path('user/manager/site/advertisings/add', views_managerSite.manager_advertisings_add, name='manageradsadd'),
    path('user/manager/site/setting', views_managerSite.manager_setting, name='managersetting'),
    path('user/manager/site/comments/reports', views_managerSite.managerReports_cmt, name='managercmtreport'),
]

News_Pannel/models.py
from django.db import models

class Ticket(models.Model):
    user = models.CharField(max_length=50)
    subject = models.CharField(max_length=100)
    ticket = models.TextField()

    def __str__(self):
        return self.user

News_Pannel/forms.py
from django import forms
from News_Account.models import User
from django.core import validators
from News_Post.models import Post, PostTag, PostGallery
from django.utils.translation import gettext_lazy as _

from News_Sitesetting.models import Send_Mail, Notification, SiteSetiing, Advertising


class change_data(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "avatar", "phone", "web", "bio"]
        labels = {
            'first_name': _('نام'),
            'last_name': _('نام خانوادگی'),
            'avatar': _('لوگو'),
            'phone': _('شماره تلفن'),
            'web': _('وبسایت'),
            'bio': _('بیوگرافی'),
        }

class change_Pw(forms.Form):
    pw1 = forms.CharField(widget=forms.PasswordInput(), label='رمزعبور <b>جدید</b> را وارد کنید:', validators=[
        validators.MinLengthValidator(5, 'رمز عبور نباید کمتر از 5 کاراکتر باشد.'),
        validators.MaxLengthValidator(25, 'رمز عبور نباید بیشتر از 25 کاراکتر باشد.')
    ], required=True)
    pw2 = forms.CharField(widget=forms.PasswordInput(), label='رمزعبور <b>جدید</b> را <b>دوباره</b> وارد کنید:', required=True)

    def clean_pw2(self):
        pw1 = self.cleaned_data.get('pw1')
        pw2 = self.cleaned_data.get('pw2')
        if pw1 != pw2:
            raise forms.ValidationError('باید مقادیر دو فیلد برابر باشند.')
        return pw2

class send_ticket(forms.Form):
    subject = forms.CharField(widget=forms.TextInput(), required=True, label='عنوان تیکت')
    ticket = forms.CharField(widget=forms.Textarea(), required=True, label='متن تیکت',validators=[
        validators.MinLengthValidator(20, 'متن تیکت نباید کمتر از 20 کاراکتر باشد.')
    ])

class send_post_postdata(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'short_description', 'categories', 'time_reading']
        labels = {
            'title': _('عنوان خبر'),
            'description': _('مشروح خبر'),
            'short_description': _('خلاصه ی خبر'),
            'categories': _('دسته بندی های خبر'),
            'time_reading': _('زمان خواندن')
        }

class send_post_tags(forms.ModelForm):
    class Meta:
        model = PostTag
        fields = ['title']
        labels = {
            'title': _('عنوان تگ'),
        }

class send_post_galleries(forms.ModelForm):
    class Meta:
        model = PostGallery
        fields = ['title']
        labels = {
            'title': _('عنوان عکس'),
        }

class Edit_User(forms.ModelForm):
    class Meta:
        model = User
        fields = ['is_active', 'is_staff', 'is_superuser', 'phone', 'web', 'bio', 'status', 'IP']
        labels = {
            'phone': _('شماره تلفن'),
            'web': _('وبسایت کاربر'),
            'bio': _('بیوگرافی'),
            'status': _('وضعیت خبری'),
            'IP': _('آی پی')
        }

class Edit_Post(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'writer', 'categories', 'image', 'description', 'short_description', 'time_reading', 'status']
        labels = {
            'title': _('عنوان خبر'),
            'writer': _('نویسنده ی خبر'),
            'image': _('تصویر محصول'),
            'description': _('مشروح خبر'),
            'short_description': _('خلاصه ی خبر'),
            'time_reading': _('زمان خواندن'),
            'categories': _('دسته بندی های خبر'),
            'status': _('وضعیت'),
        }

class sendMailForm(forms.ModelForm):
    class Meta:
        model = Send_Mail
        fields = ['subject', 'msg']
        labels = {
            'subject': _('عنوان ایمیل'),
            'msg': _('متن ایمیل'),
        }

class sendNotificationForm(forms.ModelForm):
    class Meta:
        model = Notification
        fields = ['title', 'ntf']
        labels = {
            'title': _('عنوان اعلان'),
            'ntf': _('متن اعلان'),
        }

class settingsSite(forms.ModelForm):
    class Meta:
        model = SiteSetiing
        fields = ['app_name' ,'about_us' ,'about_website' ,'place_website' ,'telegram_id' ,'whatsapp_id' ,'instagram_id' ,'scale_X' ,'scale_Y' ,'active']
        labels = {
            'app_name': _('نام فروشگاه'),
            'about_us': _('درباره ی ما'),
            'about_website': _('درباره ی وبسایت'),
            'place_website': _('آدرس وبسایت'),
            'telegram_id': _('آیدی تلگرام'),
            'whatsapp_id': _('آدرس واتساپ'),
            'instagram_id': _('آیدی اینستاگرام'),
            'scale_X': _('مقیاس ایکس در نقسه'),
            'scale_Y': _('مقیاس ایگرگ در نقشه'),
            'active': _('فعال / غیرفعال'),
        }

class addAds(forms.ModelForm):
    class Meta:
        model = Advertising
        fields = ['title']
        labels = {
            'title': _('عنوان تبلیغ'),
        }

News_Pannel/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import change_data, change_Pw, send_ticket, send_post_postdata, send_post_tags, send_post_galleries
from News_Account.models import User
from News_Post.models import FavPost, Post, Comment
from News_Sitesetting.models import Opinion, Contact
from .models import Ticket

@login_required(login_url='/sign-in')
def pannel_home(request):
    return render(request, 'home_pannel.html', {
        'allPosts': Post.objects.filter(status='p').all().order_by('-id'),
        'posts': Post.objects.filter(writer_id=request.user.id).all()
    })

@login_required(login_url='/sign-in')
def pannel_sidebar(request):
    return render(request, 'Administrator/__sidebar.html', {
        'opinionCount': Opinion.objects.count(),
        'contactCount': Contact.objects.count(),
        'reportCount': Comment.objects.filter(pre_report=True).count()
    })

@login_required(login_url='/sign-in')
def pannel_edit(request):
    change_data_form = change_data(request.POST or None, request.FILES or None, initial={
        'first_name':request.user.first_name,
        'last_name':request.user.last_name,
        'avatar':request.user.avatar,
        'phone':request.user.phone,
        'web':request.user.web,
        'bio':request.user.bio,
    })
    context = {
        'change_data_form':change_data_form
    }
    if request.POST or request.FILES:
        if change_data_form.is_valid():
            first_name = change_data_form.cleaned_data.get('first_name')
            last_name = change_data_form.cleaned_data.get('last_name')
            avatar = request.FILES.get('avatar')
            phone = change_data_form.cleaned_data.get('phone')
            web = change_data_form.cleaned_data.get('web')
            bio = change_data_form.cleaned_data.get('bio')

            thisUser = User.objects.get(id=request.user.id)
            if first_name:
                thisUser.first_name = first_name
            if last_name:
                thisUser.last_name = last_name
            if avatar:
                thisUser.avatar = avatar
            if phone:
                thisUser.phone = phone
            if web:
                thisUser.web = web
            if bio:
                thisUser.bio = bio

            thisUser.save()
            messages.info(request, 'تغییرات با موفقیت ثبت شدند.')
            return redirect('/user/dashboard')

    return render(request, 'pannel_edit.html', context)


@login_required(login_url='/sign-in')
def pannel_changePassword(request):
    changepw = change_Pw(request.POST or None)
    thisUser = request.user
    context = {
        'changepw':changepw
    }
    if changepw.is_valid():
        pw1 = changepw.cleaned_data.get('pw1')
        pw2 = changepw.cleaned_data.get('pw2')

        if pw1 == pw2:
            thisUser.set_password(pw2)
            thisUser.save()

            messages.info(request, 'رمز عبور جدید با موفقیت ثبت شد.')
            return redirect('/user/dashboard')

    return render(request, 'change_pw.html', context)


@login_required(login_url='/sign-in')
def pannel_saved(request):
    favs = FavPost.objects.filter(user_id=request.user.id).order_by('-id')
    context = {'favs':favs}
    return render(request, 'pannel_saved.html', context)


@login_required(login_url='/sign-in')
def delete_pannel_saved(request, postID):
    FavPost.objects.get(user_id=request.user.id, post_id=postID).delete()
    messages.info(request, 'خبر مورد نظر با موفقیت ازلیست بایگانی حذف شد.')
    return redirect('/user/dashboard')


@login_required(login_url='/sign-in')
def pannel_send_ticket(request):
    send_ticket_form = send_ticket(request.POST or None)
    context = {'send_ticket_form':send_ticket_form}
    if send_ticket_form.is_valid():
        subject = send_ticket_form.cleaned_data.get('subject')
        ticket = send_ticket_form.cleaned_data.get('ticket')

        Ticket.objects.create(user=request.user.username, subject=subject, ticket=ticket)
        messages.info(request, 'تیکت شما با موفقیت ثبت شد. در اسرع وقت بررسی میشود.')
        return redirect('/user/dashboard')

    return render(request, 'pannel_send_ticket.html', context)


@login_required(login_url='/sign-in')
def pannel_send_post(request):
    if request.user.status == 's' or request.user.status == 'v':
        messages.info(request, 'شما باید عضویت ویژه داشته باشید.')
        return redirect('/user/dashboard')

    sendpost = send_post_postdata(request.POST or None, request.FILES or None)

    context = {
        'sendpost': sendpost,
    }

    image = request.FILES.get('imagePost')

    if sendpost.is_valid():
        save_post: Post = sendpost.save()
        for i in sendpost.cleaned_data.get('categories'):
            save_post.categories.add(i)
        save_post.image = image
        save_post.status = 'p'
        save_post.writer = request.user

        save_post.save()
        messages.info(request, 'با تشکر، پست شما در سایت قرار گرفت ، بزودی مورد بررسی قرار خواهد گرفت.')
        return redirect('pannel:sendposttags')

    return render(request, 'pannel_send_post.html', context)


@login_required(login_url='/sign-in')
def pannel_send_post_tags(request):
    if request.user.status == 's' or request.user.status == 'v':
        messages.info(request, 'شما باید عضویت ویژه داشته باشید.')
        return redirect('/user/dashboard')

    sendposttags = send_post_tags(request.POST or None)
    selectPostuser = request.POST.get('selectPostuser')
    print(selectPostuser)

    if sendposttags.is_valid():
        saveTAG = sendposttags.save(commit=False)
        saveTAG.post = Post.objects.get(id=selectPostuser)
        saveTAG.writer = request.user
        saveTAG.save()
        messages.info(request, 'تگ پست شما با موفقیت افزوده شد. شما میتوانید چندین تگ ایجاد کنید.')
        return redirect('pannel:sendpostgalleries')

    return render(request, 'pannel_send_post_tags.html', {
        'send_post_tags':send_post_tags,
        'posts':Post.objects.filter(writer_id=request.user.id).all()
    })


@login_required(login_url='/sign-in')
def pannel_send_post_galleries(request):
    if request.user.status == 's' or request.user.status == 'v':
        messages.info(request, 'شما باید عضویت ویژه داشته باشید.')
        return redirect('/user/dashboard')

    sendpostgalleries = send_post_galleries(request.POST or request.FILES)
    selectPostuser = request.POST.get('selectPostuser')
    imagePostGall = request.FILES.get('imagePostGall')

    if sendpostgalleries.is_valid():
        saveGall = sendpostgalleries.save(commit=False)
        saveGall.post = Post.objects.get(id=selectPostuser)
        saveGall.image = imagePostGall
        saveGall.writer = request.user
        saveGall.save()
        messages.info(request, 'گالری پست شما با موفقیت ساخته شد. شما میتوانید تصاویر بیشتری به گالری خبر خود بیفزایید.')
        return redirect('pannel:home')

    return render(request, 'pannel_send_post_galleries.html', {
        'sendpostgalleries':sendpostgalleries,
        'posts': Post.objects.filter(writer_id=request.user.id).all()
    })


@login_required(login_url='/sign-in')
def pannel_convert_release(request, postID):
    if not request.user.is_superuser:
        return redirect('/')

    post = Post.objects.filter(id=postID).first()
    post.status = 'm'
    post.save()
    messages.info(request, 'پست با موفقیت منتشر شد.')
    return redirect('pannel:home')

News_Pannel/templates/change_pw.html
{% extends 'Administrator/__mainlayout.html' %}
{% block titlePageAdmin %}تغییر رمز عبور {{ request.user.username }}{% endblock %}
{% load static %}
{% load widget_tweaks %}
{% block contentPannel %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <br>
        <h4>تغییر رمز عبور</h4>
        <br>

        <div class="container">
            <div class="shadow border p-3">

                <form method="POST">
                    {% csrf_token %}

                    <div class="row p-3">
                        <div class="col-md-6 p-2">
                            <label for="{{ changepw.pw1.id_for_label }}" class="text-muted">{{ changepw.pw1.label | safe }}</label>
                            {{ changepw.pw1|add_class:'form-control form-control-sm'|attr:'placeholder: رمزعبور جدید' }}
                            {% for i in changepw.pw1.errors %}
                                <p class="f-small text-danger">{{ i }}</p>
                            {% endfor %}
                        </div>
                        <div class="col-md-6 p-2">
                            <label for="{{ changepw.pw2.id_for_label }}" class="text-muted">{{ changepw.pw2.label | safe }}</label>
                            {{ changepw.pw2|add_class:'form-control form-control-sm'|attr:'placeholder: تکرار رمز عبور جدید' }}
                            {% for i in changepw.pw2.errors %}
                                <p class="f-small text-danger">{{ i }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm float-right br-rl p-2"> ویرایش اطلاعات <i class="fa fa-edit"></i></button>
                    <br><br>
                </form>

            </div>
        </div>

    </div>
</div>


{% endblock %}

News_Pannel/templates/manager_advertisings.html
{% extends 'Administrator/__mainlayout.html' %}
{% block titlePageAdmin %}تبلیغات{% endblock %}
{% load static %}
{% load widget_tweaks %}
{% block contentPannel %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <br>
        <h4>تبلیغات</h4>
        <br>

        <div class="container">
            <div class="shadow border p-3">

                <p class="text-muted">توجه: هر تبلیغ پس از انتشار تا 12 ساعت در سایت میماند و بعد از آن از پایگاه داده حذف میشود.</p>
                <a href="{% url 'pannel:manageradsadd' %}" class="btn btn-primary btn-sm float-right">اضافه کردن تبلیغ</a><br><br>
                {% if adss %}
                    <table class="table table-hover table-borderless text-center">
                        <tr class="bg-primary text-white">
                            <th>#</th>
                            <th>عنوان تبلیغ</th>
                            <th>تصویر تبلیغ</th>
                            <th>زمان انتشار</th>
                        </tr>

                        {% for i in adss %}
                            <tr>
                                <td class="number">{{ forloop.counter }}</td>
                                <td>{{ i.title }}</td>
                                <td>
                                    <a href="{{ i.image.url }}">
                                        <img src="{{ i.image.url }}" class="imgintabs">
                                    </a>
                                </td>
                                <td>{{ i.timeStamp|timesince }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <div class="alert alert-warning">
                        هنوز تبلیغی در نشده است.
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>

{% endblock %}

News_Pannel/templates/manager_contactus.html
{% extends 'Administrator/__mainlayout.html' %}
{% block titlePageAdmin %}تماس های کاربران{% endblock %}
{% load static %}
{% load widget_tweaks %}
{% block contentPannel %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <br>
        <h4>تماس های کاربران</h4>
        <br>

        <div class="container">
            <div class="shadow border p-3">

                <table class="table table-hover table-borderless text-center">
                    <tr class="bg-primary text-white">
                        <th>#</th>
                        <th>آدرس ایمیل</th>
                        <th>عنوان تماس</th>
                        <th>تصویر ارسالی</th>
                        <th>متن پیام</th>
                        <th>زمان ارسال</th>

                    </tr>

                    {% for i in contacts %}
                    <tr>
                        <td class="number">{{ forloop.counter }}</td>
                        <td>{{ i.email }}</td>
                        <td>{{ i.subject }}</td>
                        <td>{% if i.image %}<a href="{{ i.image.url }}"><img src="{{ i.image.url }}" class="imgintabs"></a>{% else %}-{% endif %}</td>
                        <td><button class="btn btn-primary btn-sm" onclick="javascript:alert('{{ i.msg }}')">مشاهده</button></td>
                        <td>{{ i.timeStamp|timesince }} پیش</td>

                    </tr>
                    {% endfor %}
                    
                </table>

            </div>
        </div>

    </div>
</div>


{% endblock %}

News_Pannel/templates/manager_email_send.html
{% extends 'Administrator/__mainlayout.html' %}
{% block titlePageAdmin %}ارسال ایمیل {% endblock %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block contentPannel %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <br>
        <h4>ارسال ایمیل </h4>
        <br>

        <div class="container">
            <h5>تمامی ایمیل ها</h5>
            <div class="shadow border p-3">
                <table class="table table-hover table-borderless text-center">

                    <tr class="bg-primary text-white">
                        <th>#</th>
                        <th>عنوان ایمیل</th>
                        <th>وضعیت</th>
                        <th>زمان ارسال</th>
                        <th>حذف ایمیل</th>
                        <th>ارسال ایمیل</th>
                    </tr>
                    {% for allMail in allMails %}
                       <tr>
                            <td class="number">{{ forloop.counter }}</td>
                            <td>{{ allMail.subject }}</td>
                            <td>{% if allMail.sended == True %}ارسال شده{% else %}ارسال نشده{% endif %}</td>
                            <td>{% if allMail.sended == True %}{{ allMail.timeStamp | timesince }} پیش {% else %}-{% endif %}</td>
                            <td><a href="{% url 'pannel:manageremailremove' allMail.id %}" class="btn btn-sm btn-danger">حذف </a></td>
                            <td><a href="{% url 'pannel:manageremailsendMail' allMail.id %}" class="btn btn-sm btn-primary">ارسال </a></td>
                       </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

    </div>
</div>


{% endblock %}

News_Pannel/templates/manager_post.html
{% extends 'Administrator/__mainlayout.html' %}
{% block titlePageAdmin %}مدیریت اخبار{% endblock %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}
{% block contentPannel %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <br>
        <h4>مدیریت اخبار</h4>
        <br>

        <div class="container">
            <div class="shadow border p-3">

                <table class="table table-hover table-borderless text-center">
                    <tr class="bg-primary text-white">
                        <th>#</th>
                        <th>عنوان خبر</th>
                        <th>نویسنده</th>
                        <th>تصویر</th>
                        <th>خلاصه ی خبر</th>
                        <th>دسته بندی ها</th>
                        <th>زمان خواندن</th>
                        <th>تعداد بازدید</th>
                        <th>تعداد کامنت</th>
                        <th>تعداد لایک</th>
                        <th>زمان انتشار</th>
                        <th>جزئیات</th>

                    </tr>

                    {% for i in posts %}
                    <tr>
                        <td class="number">{{ forloop.counter }}</td>
                        <th><a href="{{ i.get_absolute_url }}" class="anc">{{ i.title }}</a></th>
                        <td>{{ i.writer.username }}</td>
                        <td><a href="{{ i.image.url }}"><img src="{{ i.image.url }}" alt="" class="imgintabs img-fluid"></a></td>
                        <td><button class="btn btn-primary btn-sm" onclick="javascript:alert('{{ i.short_description }}')">مشاهده</button></td>
                        <td>
                            {% for ii in i.categories.all %}
                                {{ ii.title }}{% if not forloop.last %} ، {% endif %}
                            {% endfor %}
                        </td>
                        <td><span class="number">{{ i.time_reading }}</span> دقیقه </td>
                        <td class="number">{{ i.views }}</td>
                        <td class="number">{{ i.comments_count }}</td>
                        <td class="number">{{ i.like_count }}</td>
                        <td>{{ i.timeStamp|naturalday }}</td>
                        <td><a href="{% url 'pannel:managerPostedit' i.id %}" class="btn btn-primary btn-sm">ویرایش</a></td>

                    </tr>
                    {% endfor %}

                </table>

            </div>
        </div>

    </div>
</div>


{% endblock %}

News_Pannel/templates/manager_user.html
{% extends 'Administrator/__mainlayout.html' %}
{% block titlePageAdmin %}مدیریت کاربران{% endblock %}
{% load static %}
{% load widget_tweaks %}
{% block contentPannel %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <br>
        <h4>مدیریت کاربران</h4>
        <br>

        <div class="container">
            <div class="shadow border p-3">

                <table class="table table-hover table-borderless text-center">
                    <tr class="bg-primary text-white">
                        <th>#</th>
                        <th>نام کاربری</th>
                        <th>ایمیل</th>
                        <th>نام و نام خانوادگی</th>
                        <th>IP</th>
                        <th>وضعیت کارمندی</th>
                        <th>وضعیت خبری</th>
                        <th>انتشارات</th>
                        <th>جزئیات</th>
                    </tr>
                    
                    {% for i in users %}
                    <tr>
                        <td class="number">{{ forloop.counter }}</td>
                        <th>{{ i.username }}</th>
                        <td>{{ i.email }}</td>
                        <td>{% if i.get_full_name %}{{ i.get_full_name }}{% else %}-{% endif %}</td>
                        <td>{{ i.IP }}</td>
                        <td>{% if i.is_staff %}<img src="{% static 'img/tik.png' %}" class="tikmultisize" alt="ok">{% else %}<img src="{% static 'img/multi.png' %}" class="tikmultisize" alt="ok">{% endif %}</td>
                        <th>
                            {% if i.status == 's' %}ساده{% endif %}
                            {% if i.status == 'v' %}ویژه{% endif %}
                            {% if i.status == 'g' %}خبرگذار{% endif %}
                            {% if i.status == 'n' %}خبرنگار{% endif %}
                        </th>
                        <td class="number">{{ i.posts.count }}</td>
                        <td>
                            <a href="{% url 'pannel:managerUseredit' i.id %}" class="btn btn-sm btn-primary">ویرایش</a>
                        </td>
                    </tr>
                    {% endfor %}
                    
                </table>

            </div>
        </div>

    </div>
</div>


{% endblock %}

News_Pannel/templates/pannel_saved.html
{% extends 'Administrator/__mainlayout.html' %}
{% block titlePageAdmin %}بایگانی اخبار {% endblock %}
{% load static %}
{% load widget_tweaks %}
{% block contentPannel %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <br>
        <h4>بایگانی اخبار</h4>
        <br>

        <div class="container">
            <div class="shadow border p-3">

                <div class="p-3">
                    {% if favs %}
                        {% for fav in favs %}
                            <div class="mt-2 p-3 border">
                                <a href="{{ fav.post.get_absolute_url }}" class="pl-5 anc">{{ fav.post.title }}</a>
                                <a href="{% url 'pannel:deletepostsave' fav.post.id %}" class="btn btn-sm btn-info float-right ml-1">حذف <i class="fa fa-trash"></i></a>
                                <a href="{{ fav.post.get_absolute_url }}" class="btn btn-sm btn-primary float-right">مشاهده <i class="fa fa-eye"></i></a>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-warning">
                            قسمت بایگانی اخبار شما خالی میباشد.
                        </div>
                    {% endif %}
                </div>

            </div>
        </div>

    </div>
</div>


{% endblock %}