News/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'home'
urlpatterns = [

	# Introduction Apps
	path('', include('News_Account.urls')),
	path('', include('News_Pannel.urls')),
	path('', include('News_Post.urls')),
	path('', include('News_Sitesetting.urls')),

	# Url Pages
	path('', views.home_page, name='home'),

	# partial Views
	path('', views.header_partial, name='header'),
	path('', views.bottomWriter_partial, name='writer'),
	path('', views.opinion_footer_partial, name='footerpar'),

	path('ckeditor/', include('ckeditor_uploader.urls')),
	path('captcha/', include('captcha.urls')),
	path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

News_Account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'auth'
urlpatterns = [
    path('sign-in', views.sign_in_page , name='signin'),
    path('sign-out', views.sign_out_page , name='signout'),
    path('sign-up', views.sign_up_page , name='signup'),

    # path('signup/', views.signup.as_view(), name='signup'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),

]

News_Pannel/urls.py
from django.urls import path
from . import views, views_managerUser, views_managerSite

app_name = 'pannel'
urlpatterns = [
    path('user/dashboard', views.pannel_home, name='home'),
    path('user/edit', views.pannel_edit, name='edit'),
    path('user/change-pw', views.pannel_changePassword, name='changepw'),
    path('user/saved', views.pannel_saved, name='saved'),
    path('user/delete/saved/<int:postID>', views.delete_pannel_saved, name='deletepostsave'),
    path('user/send-ticket', views.pannel_send_ticket, name='sendticket'),
    path('user/send/post', views.pannel_send_post, name='sendpost'),
    path('user/send/post/tags', views.pannel_send_post_tags, name='sendposttags'),
    path('user/send/post/galleries', views.pannel_send_post_galleries, name='sendpostgalleries'),
    path('user/release/<int:postID>', views.pannel_convert_release, name='releasepost'),

    # manager User
    path('user/manager/users', views_managerUser.managerUser, name='managerUser'),
    path('user/manager/posts', views_managerUser.managerPost, name='managerPost'),
    path('user/manager/users/edit/<int:userID>', views_managerUser.managerUser_edit, name='managerUseredit'),
    path('user/manager/posts/edit/<int:postID>', views_managerUser.managerPost_edit, name='managerPostedit'),
    path('user/manager/emails', views_managerUser.manageremail, name='manageremail'),
    path('user/manager/emails/send', views_managerUser.manageremailSend, name='manageremailsend'),
    path('user/manager/emails/remove/<int:emailID>', views_managerUser.manageremailSend_remove, name='manageremailremove'),
    path('user/manager/emails/send/<int:emailID>', views_managerUser.manageremailSend_sendmail, name='manageremailsendMail'),
    path('user/manager/charts', views_managerUser.managercharts, name='managercharts'),
    path('user/manager/notifications', views_managerUser.manager_notifications, name='managernotifications'),

    # manager Site
    path('user/manager/site/contact-us', views_managerSite.manager_contactus, name='managercontact'),
    path('user/manager/site/opinions', views_managerSite.manager_opinions, name='manageropinion'),
    path('user/manager/site/advertisings', views_managerSite.manager_advertisings, name='managerads'),
    path('user/manager/site/advertisings/add', views_managerSite.manager_advertisings_add, name='manageradsadd'),
    path('user/manager/site/setting', views_managerSite.manager_setting, name='managersetting'),
    path('user/manager/site/comments/reports', views_managerSite.managerReports_cmt, name='managercmtreport'),
]

News_Post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('post/list/', views.PostList.as_view(), name='list'),
    path('post/detail/<int:postID>/<str:postTITLE>', views.post_detail, name='detail'),
    path('post/search/', views.searchPost.as_view(), name='search'),
    path('post/tag/<str:tagTitle>', views.searchPostTag.as_view(), name='tag'),
    path('post/category/<str:CategoryTitle>', views.searchPostCateGory.as_view(), name='category'),
    # path('post/specific/', views.postSpecific.as_view(), name='postSpecific'),      #asdfasdfasfa
    path('post/many/<int:Many>', views.postMany.as_view(), name='many'),
    path('post/time/<str:postTime>', views.postTime.as_view(), name='time'),
    path('post/comments/report/<int:commentID>/<int:postID>', views.reportComment, name='reportComment'),
    path('post/comments/remove/<int:commentID>/<int:postID>', views.removeComment, name='removeComment'),
    path('post/like', views.like_post_page, name='like'),
    path('post/fav', views.fav_post_page, name='fav'),
    path('post/recent', views.postListRecent.as_view(), name='recent'),
    path('post/most-views', views.postListMostViews.as_view(), name='mostviews'),
    path('post/popular', views.postListPopular.as_view(), name='popular'),
    path('post/hot', views.postListHot.as_view(), name='hot'),

    # Partials
    path('post/list/sidebar/list/partial', views.sidebar_list_partial),
]

News_Sitesetting/urls.py
from django.urls import path
from . import views

app_name = 'sitesetting'
urlpatterns = [
    path('about-us', views.aboutus_page, name='aboutus'),
    path('contact-us', views.contactus_page, name='contactus'),

]

templates/shared/__bottomwriter.html
{% load static %}
<!-- mini div -->
<div class="py-2">
    <div class="container">
        <div class="row align-items-center text-center">
            <div class="col-lg-4 text-lg-left f-small">تمام حقوق مادی و معنوی این سایت متعلق به وبسایت می باشد و استفاده از مطالب با ذکر منبع بلامانع است.</div>
            <div class="col-lg-4 my-3 my-lg-0 text-center">

                {% if SiteSetiing.instagram_id %}
                    <a href="{{ SiteSetiing.instagram_id }}" target="_blank" class="c-dark f-icon no-decoration mr-2 icon">
                        <i class="fa fa-instagram  wow animate__animated animate__zoomIn" data-wow-delay="1s"></i>
                    </a>
                {% endif %}
                {% if SiteSetiing.telegram_id %}
                    <a href="{{ SiteSetiing.telegram_id }}" target="_blank" class="c-dark f-icon no-decoration mr-2 icon">
                        <i class="fa fa-telegram  wow animate__animated animate__zoomIn" data-wow-delay="1.5s"></i>
                    </a>
                {% endif %}
                {% if SiteSetiing.whatsapp_id %}
                    <a href="{{ SiteSetiing.whatsapp_id }}" target="_blank" class="c-dark f-icon no-decoration mr-2 icon">
                        <i class="fa fa-whatsapp  wow animate__animated animate__zoomIn" data-wow-delay="1s"></i>
                    </a>
                {% endif %}

            </div>
            <div class="col-lg-4 text-lg-right mt-2">
                <p>طراح و برنامه نویس: <a href="https://www.instagram.com/saeedreza_wu" target="_blank" class="c-dark font-weight-bolder no-decoration icon wow animate__animated animate__fadeIn">سعیدرضا غضنفری</a></p>
            </div>
        </div>
    </div>
</div>

templates/shared/__footer.html
{% load widget_tweaks %}
{% load static %}
<section class="bg-map">
    <br><br><br><br><br>
    <div class="container">
        <div class="text-center">
            <h5 class="c-warning">با ارسال نظر ما را دلگرم کنید و حامی ما باشید</h5>
            <br>
        </div>
        <form method="POST">{% csrf_token %}
            <div class="row mb-4">
                <div class="col-md-6">
                    <div class="form-group">
                        {{ opinionform.name|add_class:'form-control form-control-home form-control-lg'|attr:'placeholder:* نام خود را وارد کنید:' }}
                        {% for err in opinionform.name.errors %}
                            <p class="text-danger f-small">{{ err }}</p>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ opinionform.email|add_class:'form-control form-control-home form-control-lg'|attr:'placeholder:* ایمیل خود را وارد کنید:' }}
                        {% for err in opinionform.email.errors %}
                            <p class="text-danger f-small">{{ err }}</p>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ opinionform.subject|add_class:'form-control form-control-home form-control-lg'|attr:'placeholder:*عنوان ایمیل خود را وارد کنید:' }}
                        {% for err in opinionform.subject.errors %}
                            <p class="text-danger f-small">{{ err }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-6">
                    {{ opinionform.msg|add_class:'form-control form-control-home form-control-home-media form-control-lg p-3'|attr:'placeholder:* متن ایمیل خود را وارد کنید:'|attr:'rows:5' }}
                    {% for err in opinionform.msg.errors %}
                        <p class="text-danger f-small">{{ err }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="text-center">
                <div id="success"></div>
                <button class="btn bt-warning-beauti btn-xl" id="sendMessageButton" type="submit">ارسال ایمیل</button>
            </div>

        </form>
    </div>

    <!-- to top -->
    <a href="#" id="toTop" class="animate__animated">
        <img src="{% static 'img/top4.png' %}" class="radius img-fluid border" alt="image to top">
    </a>

</section>

templates/shared/__footer_ref.html
{% load static %}
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
<script type="text/javascript" src="{% static 'frameworks/chart.js' %}"></script>
<script type="text/javascript" src="{% static 'frameworks/wow.js' %}"></script>
<script type="text/javascript" src="{% static 'frameworks/owl.carousel.min.js' %}"></script>

templates/shared/__header.html
{% load static %}
<!-- start header -->
<header class="divimagefullmeasure">
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light " id="topnavbar">

        <a class="navbar-brand c-warning ml-2">
            <div class="animate__animated animate__flipInX">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'pannel:home' %}" class="c-warning no-decoration"><img src="{% if request.user.avatar %}{{ request.user.avatar.url }}{% else %}{% static 'img/newsbrand.jpg' %}{% endif %}" class="img-fluid radius sizeavatarnav " alt=""> <span>{% if request.user.get_full_name %}{{ request.user.get_full_name }}{% else %}{{ request.user.username }}{% endif %}</span></a>&nbsp;&nbsp;<a href="{% url 'auth:signout' %}" class=" f-small c-white ml-0"><i class="fa fa-power-off" title="خروج"></i></a>
                {% else %}
                    <a href="{% url 'home' %}" class="c-warning no-decoration"><b>  {{ SiteSetiing.app_name }} </b></a>
                {% endif %}
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon "></span>
        </button>

        <div class="collapse navbar-collapse text-center ml-200" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link c-warning mr-3 ml-3 {% if request.path == '/' %}active-navlink{% endif %}" href="{% url 'home' %}">خانه</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link c-warning mr-3 {% if '/post' in request.path %}active-navlink{% endif %}" href="{% url 'post:list' %}">اخبار</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link c-warning mr-3 {% if request.path == '/about-us' %}active-navlink{% endif %}" href="{% url 'sitesetting:aboutus' %}">درباره ی ما</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link c-warning mr-3 {% if request.path == '/contact-us' %}active-navlink{% endif %}" href="{% url 'sitesetting:contactus' %}">تماس با ما</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link c-warning mr-3" href="{% url 'pannel:home' %}"> پنل کاربری </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link c-warning mr-3" href="{% url 'auth:signout' %}">خروج</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link c-warning mr-3" href="{% url 'auth:signin' %}">ورود</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link c-warning mr-3" href="{% url 'auth:signup' %}">ثبتنام</a>
                    </li>
                {% endif %}
            </ul>
            <!-- notification button -->
            {% if request.user.is_authenticated %}
            <a id="opeclonotit" class="nav-link float-left c-warning mr-3">
                {% if noticount != 0 %}<span class="badge  badge-pill badge-danger m-neg-15 number">{{ noticount }}</span>{% endif %}
                <span><i class="fa fa-bell border-iconNot radius p-2"></i></span>
            </a>
            {% endif %}

            <form class="form-inline my-2 d-lg-none" method="GET" action="{% url 'post:search' %}">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control br-r" placeholder="جستجوی خبر" name="post">
                    <div class="input-group-prepend">
                        <button type="submit" class="input-group-button btn bt-warning br-l"><i class="fa fa-search"></i></button>
                    </div>    
                </div>
            </form>

        </div>
    </nav>

    <!-- nofification -->
    {% if request.user.is_authenticated %}
    <div class="b-dark c-white p-4 radius-sm shadow" id="b-notificat">

        <h4 class="p-3 ">اعلانات <i class="fa fa-bell c-warning"></i>
            <a class="c-warning float-right" id="closeAnchotnot"><i class="fa fa-close"></i></a>
        </h4>

        {% if notifications and request.user.is_authenticated %}

            {% for i in notifications %}
                {% if request.user.status == 's' and i.is_simple == True %}
                    <div class="b-white c-dark m-3 p-3 border radius-sm">
                        <span class="f-small c-muted float-right"><i class="fa fa-clock"></i> {{ i.timeStamp | timesince }} پیش </span>
                        <br><br>
                        <p><b>{{ i.title }} {% if i.is_specific %}<span class="badge badge-danger">ویژه</span>{% endif %}</b></p>
                        <p class="paragraph">
                            {{ i.ntf }}
                        </p>
                    </div>
                {% endif %}
            {% endfor %}

            {% for i in notifications %}
                {% if request.user.status == 'v' and i.is_specific == True %}
                    <div class="b-white c-dark m-3 p-3 border radius-sm">
                        <span class="f-small c-muted float-right"><i class="fa fa-clock"></i> {{ i.timeStamp | timesince }} پیش </span>
                        <br><br>
                        <p><b>{{ i.title }} {% if i.is_specific %}<span class="badge badge-danger">ویژه</span>{% endif %}</b></p>
                        <p class="paragraph">
                            {{ i.ntf }}
                        </p>
                    </div>
                {% endif %}
            {% endfor %}

            {% for i in notifications %}
                {% if request.user.status == 'g' and i.is_newsTransition == True %}
                    <div class="b-white c-dark m-3 p-3 border radius-sm">
                        <span class="f-small c-muted float-right"><i class="fa fa-clock"></i> {{ i.timeStamp | timesince }} پیش </span>
                        <br><br>
                        <p><b>{{ i.title }} {% if i.is_specific %}<span class="badge badge-danger">ویژه</span>{% endif %}</b></p>
                        <p class="paragraph">
                            {{ i.ntf }}
                        </p>
                    </div>
                {% endif %}
            {% endfor %}

            {% for i in notifications %}
                {% if request.user.status == 'n' and i.is_reporter == True %}
                    <div class="b-white c-dark m-3 p-3 border radius-sm">
                        <span class="f-small c-muted float-right"><i class="fa fa-clock"></i> {{ i.timeStamp | timesince }} پیش </span>
                        <br><br>
                        <p><b>{{ i.title }} {% if i.is_specific %}<span class="badge badge-danger">ویژه</span>{% endif %}</b></p>
                        <p class="paragraph">
                            {{ i.ntf }}
                        </p>
                    </div>
                {% endif %}
            {% endfor %}

        {% else %}
            <div class="alert alert-warning m-3">
                هیچ اعلانی برای شما منتشر نشده است.
            </div>
        {% endif %}

    </div>
    {% endif %}

    <!-- center message -->
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4 c-white text-center mt-400">
            <h1 class="f-large font-weight-bolder wow animate__animated animate__fadeInUp" data-wow-delay="1s"> وبسایت خبری {{ SiteSetiing.app_name }} </h1>
            <br>
            <h6 class=" wow animate__animated animate__fadeIn" data-wow-delay="0.3s"> <i class="fa fa-check c-warning"></i> جذابترین، داغترین و آخرین اخبار را از سایت ما ببینید. </h6>
            <h6 class=" wow animate__animated animate__fadeIn" data-wow-delay="0.5s"> <i class="fa fa-check c-warning"></i> شما میتوانید برای خبررسانی به ما بپیوندید.</h6>
            <h6 class=" wow animate__animated animate__fadeIn" data-wow-delay="0.7s"> <i class="fa fa-check c-warning"></i> برای ستاره شدن به ما بپیوندید.</h6>
        </div>
        <div class="col-md-4 mt-400-brand">
            <img src="{% if SiteSetiing.logo.url %}{{ SiteSetiing.logo.url }}{% else %}{% static 'img/newsbrand.jpg' %}{% endif %}" class="img-fluid radius ml-4" alt="this is news Image">
            <br>    
            <br>    
            <form class="form-inline my-2 text-center" method="GET" action="{% url 'post:search' %}">
                <div class="input-group" >
                    <input type="text" class="form-control form-control-lg br-r" placeholder="جستجوی خبر" name="post">
                    <div class="input-group-prepend">
                        <button type="submit" class="input-group-button btn bt-warning br-l"><i class="fa fa-search"></i></button>
                    </div>    
                </div>
            </form>
        </div>
    </div>
</header>
<!-- end header -->

templates/shared/__header_ref.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="icon" href="{% static 'img/newsbrand.jpg' %}">
<meta name="description" content="این یک پکیج تمرینی برای وبسایت خبری میباشد.">
<!-- CDN -->
<link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css" integrity="sha384-vus3nQHTD+5mpDiZ4rkEPlnkcyTP+49BhJ4wJeJunw06ZAp+wzzeBPUXr42fi8If" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!-- leaflet -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>

<!-- External files2 -->
<link rel="stylesheet" href="{% static 'css/configure.css' %}">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<link rel="stylesheet" href="{% static 'frameworks/Animate.css' %}">
<link rel="stylesheet" href="{% static 'frameworks/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'frameworks/owl.theme.default.min.css' %}">

templates/shared/__main_layout.html
{% load render_partial %}
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>

    {% include 'shared/__header_ref.html' %}
    <title>{% block titlePage %}پایگاه خبری | خانه{% endblock %}</title>

</head>
<body>

<!-- loading page -->
<div class="text-center loaderDIV">
    <div class="mx-auto">
        <img src="{% static 'img/preload.gif' %}" alt="this is preload page" class="custom-preload-image img-fluid">
    </div>
</div>

{% if not request.path == '/sign-in' %}
    {% if not request.path == '/sign-up' %}
        {% render_partial 'News.views.header_partial' %}
    {% endif %}
{% endif %}

{% block content %}{% endblock %}

{% if not request.path == '/sign-in' or request.path == '/sign-up' %}
    {% if not request.path == '/sign-up' %}
        {% render_partial 'News.views.opinion_footer_partial' %}
    {% endif %}
{% endif %}

<!-- alert Massage -->
<div class="messagesClass">
    {% if messages %}
        {% for message in messages %}
            <div class="alert f-small b-dark c-warning alert-dismissible fade show removeAlertMsg" role="alert">
                {{ message | safe }}
                <button type="button" class="close btn" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% if not request.path == '/sign-in' or request.path == '/sign-up' %}
    {% if not request.path == '/sign-up' %}
        {% render_partial 'News.views.bottomWriter_partial' %}
    {% endif %}
{% endif %}

{% include 'shared/__footer_ref.html' %}

<script>

// pre Load
document.onreadystatechange = function() {
    if (document.readyState !== "complete") {
        setTimeout(()=>{
            $('body').css({'visibility':'hidden', 'backgroundColor':'white'});
            $('.loaderDIV').css({'visibility':'visible'});
        },500)
    } else {
        setTimeout(() => {
            $('.loaderDIV').css({'display':'none'});
            $('body').css({'visibility':'visible', 'backgroundColor':'initial'});
        }, 500);
    }
};

// owl carousel
var owl = $('.owl-carousel');
owl.owlCarousel({
    items:3,
    loop:false,
    margin:10,
    rtl: true,
    autoplay:true,
    autoplayTimeout:1000,
    autoplayHoverPause:false,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            // nav:true
        },
        600:{
            items:2,
            nav:false
        },
        1000:{
            items:3,
            // nav:true,
            loop:false
        }
    }
});

</script>
<script> new WOW().init(); </script>
</body>
</html>