News/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'home'
urlpatterns = [

	# Introduction Apps
	path('', include('News_Account.urls')),
	path('', include('News_Pannel.urls')),
	path('', include('News_Post.urls')),
	path('', include('News_Sitesetting.urls')),

	# Url Pages
	path('', views.home_page, name='home'),

	# partial Views
	path('', views.header_partial, name='header'),
	path('', views.bottomWriter_partial, name='writer'),
	path('', views.opinion_footer_partial, name='footerpar'),

	path('ckeditor/', include('ckeditor_uploader.urls')),
	path('captcha/', include('captcha.urls')),
	path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

News_Account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'auth'
urlpatterns = [
    path('sign-in', views.sign_in_page , name='signin'),
    path('sign-out', views.sign_out_page , name='signout'),
    path('sign-up', views.sign_up_page , name='signup'),

    # path('signup/', views.signup.as_view(), name='signup'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),

]

News_Pannel/urls.py
from django.urls import path
from . import views, views_managerUser, views_managerSite

app_name = 'pannel'
urlpatterns = [
    path('user/dashboard', views.pannel_home, name='home'),
    path('user/edit', views.pannel_edit, name='edit'),
    path('user/change-pw', views.pannel_changePassword, name='changepw'),
    path('user/saved', views.pannel_saved, name='saved'),
    path('user/delete/saved/<int:postID>', views.delete_pannel_saved, name='deletepostsave'),
    path('user/send-ticket', views.pannel_send_ticket, name='sendticket'),
    path('user/send/post', views.pannel_send_post, name='sendpost'),
    path('user/send/post/tags', views.pannel_send_post_tags, name='sendposttags'),
    path('user/send/post/galleries', views.pannel_send_post_galleries, name='sendpostgalleries'),
    path('user/release/<int:postID>', views.pannel_convert_release, name='releasepost'),

    # manager User
    path('user/manager/users', views_managerUser.managerUser, name='managerUser'),
    path('user/manager/posts', views_managerUser.managerPost, name='managerPost'),
    path('user/manager/users/edit/<int:userID>', views_managerUser.managerUser_edit, name='managerUseredit'),
    path('user/manager/posts/edit/<int:postID>', views_managerUser.managerPost_edit, name='managerPostedit'),
    path('user/manager/emails', views_managerUser.manageremail, name='manageremail'),
    path('user/manager/emails/send', views_managerUser.manageremailSend, name='manageremailsend'),
    path('user/manager/emails/remove/<int:emailID>', views_managerUser.manageremailSend_remove, name='manageremailremove'),
    path('user/manager/emails/send/<int:emailID>', views_managerUser.manageremailSend_sendmail, name='manageremailsendMail'),
    path('user/manager/charts', views_managerUser.managercharts, name='managercharts'),
    path('user/manager/notifications', views_managerUser.manager_notifications, name='managernotifications'),

    # manager Site
    path('user/manager/site/contact-us', views_managerSite.manager_contactus, name='managercontact'),
    path('user/manager/site/opinions', views_managerSite.manager_opinions, name='manageropinion'),
    path('user/manager/site/advertisings', views_managerSite.manager_advertisings, name='managerads'),
    path('user/manager/site/advertisings/add', views_managerSite.manager_advertisings_add, name='manageradsadd'),
    path('user/manager/site/setting', views_managerSite.manager_setting, name='managersetting'),
    path('user/manager/site/comments/reports', views_managerSite.managerReports_cmt, name='managercmtreport'),
]

templates/Administrator/__footer_ref.html
{% load static %}
<script type="text/javascript" src="{% static 'js/administrator.js' %}"></script>
<script type="text/javascript" src="{% static 'frameworks/chart.js' %}"></script>

templates/Administrator/__header_ref.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="icon" href="./assets/img/newsbrand.jpg">
<meta name="description" content="این یک پکیج تمرینی برای وبسایت خبری میباشد.">

<!-- CDN -->
<link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css" integrity="sha384-vus3nQHTD+5mpDiZ4rkEPlnkcyTP+49BhJ4wJeJunw06ZAp+wzzeBPUXr42fi8If" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!-- leaflet -->
{#    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" /> #}
{#    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>#}

<!-- External files2 -->
<link rel="stylesheet" href="{% static 'css/configure.css' %}">
<link rel="stylesheet" href="{% static 'css/administrator.css' %}">

templates/Administrator/__mainlayout.html
{% load static %}
{% load render_partial %}
<!DOCTYPE html>
<html lang="fa">
<head>

    {% include 'Administrator/__header_ref.html' %}
    <title>{% block titlePageAdmin %}{% endblock %}</title>

</head>
<body>

    <!-- loading page -->
    <div class="text-center loaderDIV">
        <div class="mx-auto">
            <img src="{% static 'img/preload.gif' %}" alt="this is preload page" class="custom-preload-image img-fluid">
        </div>
    </div>

    {% include 'Administrator/__topnavbar.html' %}

    <div id="wrapper" class="toggled">

        <!-- Sidebar -->
        {% render_partial 'News_Pannel.views.pannel_sidebar' %}

        <!-- content -->
        {% block contentPannel %}{% endblock %}

    </div>

    <!-- alert Massage -->
    <div class="messagesClass">
        {% if messages %}
            {% for message in messages %}
                <div class="alert bg-primary text-white alert-dismissible fade show removeAlertMsg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="close btn" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

{% include 'Administrator/__footer_ref.html' %}

<script>
{#  PreLoad Page  #}
document.onreadystatechange = function() {
    if (document.readyState !== "complete") {
        setTimeout(()=>{
            $('body').css({'visibility':'hidden', 'backgroundColor':'white'});
            $('.loaderDIV').css({'visibility':'visible'});
        },500)
    } else {
        setTimeout(() => {
            $('.loaderDIV').css({'display':'none'});
            $('body').css({'visibility':'visible', 'backgroundColor':'initial'});
        }, 500);
    }
};
{% if request.path == '/user/manager/charts' %}

    {% render_partial 'News_Pannel.views_managerUser.chart_code_partial' %}

{% endif %}
</script>
</body>
</html>

templates/Administrator/__sidebar.html
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <br>
        <li class="mt-1"> <a href="{% url 'pannel:home' %}" {% if request.path == '/user/dashboard' %}class="activeAdminnav"{% endif %}>داشبورد</a> </li>
        <li class="mt-1"> <a href="{% url 'pannel:edit' %}" {% if request.path == '/user/edit' %}class="activeAdminnav"{% endif %}>ویرایش اطلاعات</a> </li>
        <li class="mt-1"> <a href="{% url 'pannel:changepw' %}" {% if request.path == '/user/change-pw' %}class="activeAdminnav"{% endif %}>تغییر رمز عبور</a></li>
        <li class="mt-1"> <a href="{% url 'pannel:saved' %}" {% if request.path == '/user/saved' %}class="activeAdminnav"{% endif %}>بایگانی اخبار</a> </li>
        <li class="mt-1"> <a href="{% url 'pannel:sendticket' %}" {% if request.path == '/user/send-ticket' %}class="activeAdminnav"{% endif %}>ارسال تیکت</a> </li>
        {% if request.user.status == 'g' or request.user.status == 'n' %}
            <li class="mt-1"> <a data-toggle="collapse" href="#collapseExample1" role="button"> ارسال خبر <span class="text-primary f-small">({% if request.user.status == 'n' %}خبرنگار{% endif %}{% if request.user.status == 'g' %}خبرگذار{% endif %})</span> </a> </li>
            <div id="collapseExample1" class="collapse show">
                <li class="mt-1"> <a href="{% url 'pannel:sendpost' %}" {% if request.path == '/user/send/post' %}class="activeAdminnav"{% endif %}><i class="fa fa-minus f-small text-primary"></i> ایجاد پست</a> </li>
                <li class="mt-1"> <a href="{% url 'pannel:sendposttags' %}" {% if request.path == '/user/send/post/tags' %}class="activeAdminnav"{% endif %}><i class="fa fa-minus f-small text-primary"></i> افزودن تگ</a> </li>
                <li class="mt-1"> <a href="{% url 'pannel:sendpostgalleries' %}" {% if request.path == '/user/send/post/galleries' %}class="activeAdminnav"{% endif %}><i class="fa fa-minus f-small text-primary"></i> ایجاد گالری</a> </li>
            </div>
        {% endif %}

        {% if request.user.is_superuser %}
            <hr class="bg-white">

            <li class="mt-1"> <a href="{% url 'pannel:managerUser' %}" {% if request.path == '/user/manager/users' %}class="activeAdminnav"{% endif %}>مدیریت کاربران</a> </li>
            <li class="mt-1"> <a href="{% url 'pannel:managerPost' %}" {% if request.path == '/user/manager/posts' %}class="activeAdminnav"{% endif %}>مدیریت اخبار</a> </li>
            <li class="mt-1"> <a data-toggle="collapse" href="#collapseExample2" role="button"> مدیریت ایمیل ها </a> </li>
            <div id="collapseExample2" class="collapse show">
                <li class="mt-1"> <a href="{% url 'pannel:manageremail' %}" {% if request.path == '/user/manager/emails' %}class="activeAdminnav"{% endif %}><i class="fa fa-minus f-small text-primary"></i> ایجاد ایمیل</a> </li>
                <li class="mt-1"> <a href="{% url 'pannel:manageremailsend' %}" {% if '/user/manager/emails/send' in request.path %}class="activeAdminnav"{% endif %}><i class="fa fa-minus f-small text-primary"></i>ارسال ایمیل</a> </li>
            </div>
            <li class="mt-1"> <a href="{% url 'pannel:managercharts' %}" {% if request.path == '/user/manager/charts' %}class="activeAdminnav"{% endif %}>نمودار ها</a> </li>
            <li class="mt-1"> <a href="{% url 'pannel:managernotifications' %}" {% if request.path == '/user/manager/notifications' %}class="activeAdminnav"{% endif %}>اعلانات سایت</a> </li>


            <hr class="bg-white">


            <li class="mt-1"> <a href="{% url 'pannel:managercontact' %}"  {% if request.path == '/user/manager/site/contact-us' %}class="activeAdminnav"{% endif %}> تماس باما <span class="text-primary f-small number"> ({{ contactCount }}) </span> </a></li>
            <li class="mt-1"> <a href="{% url 'pannel:manageropinion' %}"  {% if request.path == '/user/manager/site/opinions' %}class="activeAdminnav"{% endif %}> نظرات <span class="text-primary f-small number"> ({{ opinionCount }}) </span></a> </li>
            <li class="mt-1"> <a href="{% url 'pannel:managercmtreport' %}"  {% if request.path == '/user/manager/site/comments/reports' %}class="activeAdminnav"{% endif %}> گزارش ها <span class="text-primary f-small number"> ({{ reportCount }}) </span></a> </li>
            <li class="mt-1"> <a href="{% url 'pannel:managerads' %}"  {% if request.path == '/user/manager/site/advertisings' %}class="activeAdminnav"{% endif %}>تبلیغات</a> </li>
            <li class="mt-1"> <a href="{% url 'pannel:managersetting' %}"  {% if request.path == '/user/manager/site/setting' %}class="activeAdminnav"{% endif %}>تنظیمات سایت</a> </li>

            <hr class="bg-white">

        {% endif %}

        <li class="mt-1"> <a href="{% url 'auth:signout' %}">خروج از حساب کاربری  </a> </li>

        <br><br><br><br>
    </ul>
</div>

templates/Administrator/__topnavbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-dark bg-primary">

    <a href="#menu-toggle" id="menu-toggle" class="navbar-brand">
        <span class="navbar-toggler-icon"></span>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"> <a class="nav-link" href="{% url 'pannel:edit' %}">
                <img src="{% if request.user.avatar %}{{ request.user.avatar.url }}{% else %}{% static 'img/newsbrand.jpg' %}{% endif %}" class="img-fluid sizeimgprotop" alt="{{ request.user.username }}">
                <span class="text-white font-ava">{% if request.user.get_full_name %}{{ request.user.get_full_name }}{% else %}{{ request.user.username }}{% endif %}</span> -
                <span class="text-white font-avaa">{% if request.user.status == 'v' %}ویژه{% endif %}{% if request.user.status == 'g' %}خبرگذار{% endif %}{% if request.user.status == 'n' %}خبرنگار{% endif %}</span>
            </a> </li>
            <li class="nav-item py-3 ml-3"> <a class="nav-link" href="/">طلا نیوز</a> </li>
            <li class="nav-item py-3"> <a class="nav-link" href="{% url 'auth:signout' %}">خروج</a> </li>
        </ul>
        <form class="form-inline my-2 my-md-0"> </form>
    </div>
</nav>